### ISSUE TITLE
Panic in migration tool on anacrolix/torrent

### ISSUE THREAD

**Issue by anacrolix** [zombiezen/go-sqlite#29]
Brilliant project idea. I decided to try it out in some of my usage of `crawshaw.io/sqlite`. Running `cmd/zombiezen-sqlite-migrate@v0.2.1` on https://github.com/anacrolix/torrent/commit/8e5ae65837e395430c1c202eb9274f3af335e83c:

```
~/go/src/github.com/anacrolix/torrent$ zombiezen-sqlite-migrate ./...
zombiezen-sqlite-migrate: loading packages...
zombiezen-sqlite-migrate: packages loaded
diff -u /Users/anacrolix/go/src/github.com/anacrolix/torrent/storage/sqlite-piece-completion.go /var/folders/rx/s8fbr8m17nvg88dq7lkblhz00000gn/T/zombiezen-sqlite-1540460039.go
--- /Users/anacrolix/go/src/github.com/anacrolix/torrent/storage/sqlite-piece-completion.go	2021-11-01 11:46:47.000000000 +1100
+++ /var/folders/rx/s8fbr8m17nvg88dq7lkblhz00000gn/T/zombiezen-sqlite-1540460039.go	2021-11-19 15:47:18.000000000 +1100
@@ -8,9 +8,9 @@
 	"path/filepath"
 	"sync"
 
-	"crawshaw.io/sqlite"
-	"crawshaw.io/sqlite/sqlitex"
 	"github.com/anacrolix/torrent/metainfo"
+	"zombiezen.com/go/sqlite"
+	"zombiezen.com/go/sqlite/sqlitex"
 )
 
 type sqlitePieceCompletion struct {
panic: interface conversion: types.Type is *types.Interface, not *types.Named [recovered]
	panic: interface conversion: types.Type is *types.Interface, not *types.Named

goroutine 1 [running]:
golang.org/x/tools/go/ast/astutil.Apply.func1()
	/Users/anacrolix/go/pkg/mod/golang.org/x/tools@v0.1.0/go/ast/astutil/rewrite.go:47 +0x89
panic({0x124f280, 0xc00190c330})
	/Users/anacrolix/src/go1.17/src/runtime/panic.go:1038 +0x215
main.process.func1(0xc001eba250)
	/Users/anacrolix/go/pkg/mod/zombiezen.com/go/sqlite/cmd/zombiezen-sqlite-migrate@v0.2.1/migrate.go:326 +0xc52
golang.org/x/tools/go/ast/astutil.(*application).apply(0xc001eba240, {0x12f79c0, 0xc001b97fc0}, {0x1285cfd, 0xc001b97fc0}, 0x123cd60, {0x12f7b28, 0xc00207dea0})
	/Users/anacrolix/go/pkg/mod/golang.org/x/tools@v0.1.0/go/ast/astutil/rewrite.go:198 +0x202
golang.org/x/tools/go/ast/astutil.(*application).applyList(0xc001eba240, {0x12f79c0, 0xc001b97fc0}, {0x1285cfd, 0x5})
	/Users/anacrolix/go/pkg/mod/golang.org/x/tools@v0.1.0/go/ast/astutil/rewrite.go:473 +0xae
golang.org/x/tools/go/ast/astutil.(*application).apply(0xc001eba240, {0x12f79e8, 0xc001b377d0}, {0x12855f9, 0x0}, 0x8, {0x12f79c0, 0xc001b97fc0})
	/Users/anacrolix/go/pkg/mod/golang.org/x/tools@v0.1.0/go/ast/astutil/rewrite.go:220 +0x15f5
golang.org/x/tools/go/ast/astutil.(*application).applyList(0xc001eba240, {0x12f79e8, 0xc001b377d0}, {0x12855f9, 0x4})
	/Users/anacrolix/go/pkg/mod/golang.org/x/tools@v0.1.0/go/ast/astutil/rewrite.go:473 +0xae
golang.org/x/tools/go/ast/astutil.(*application).apply(0xc001eba240, {0x12f7bf0, 0xc002113980}, {0x1287927, 0x0}, 0x0, {0x12f79e8, 0xc001b377d0})
	/Users/anacrolix/go/pkg/mod/golang.org/x/tools@v0.1.0/go/ast/astutil/rewrite.go:226 +0x1ba5
golang.org/x/tools/go/ast/astutil.(*application).apply(0xc001eba240, {0x12f79c0, 0xc0016c6000}, {0x1285731, 0x5}, 0xc000ae13b0, {0x12f7bf0, 0xc002113980})
	/Users/anacrolix/go/pkg/mod/golang.org/x/tools@v0.1.0/go/ast/astutil/rewrite.go:295 +0x1352
golang.org/x/tools/go/ast/astutil.(*application).apply(0xc001eba240, {0x12f79e8, 0xc001b37800}, {0x12855f9, 0x8}, 0xc000ae13a8, {0x12f79c0, 0xc0016c6000})
	/Users/anacrolix/go/pkg/mod/golang.org/x/tools@v0.1.0/go/ast/astutil/rewrite.go:221 +0x1645
golang.org/x/tools/go/ast/astutil.(*application).applyList(0xc001eba240, {0x12f79e8, 0xc001b37800}, {0x12855f9, 0x4})
	/Users/anacrolix/go/pkg/mod/golang.org/x/tools@v0.1.0/go/ast/astutil/rewrite.go:473 +0xae
golang.org/x/tools/go/ast/astutil.(*application).apply(0xc001eba240, {0x12f7ab0, 0xc0021139f8}, {0x12868f9, 0x4}, 0x0, {0x12f79e8, 0xc001b37800})
	/Users/anacrolix/go/pkg/mod/golang.org/x/tools@v0.1.0/go/ast/astutil/rewrite.go:226 +0x1ba5
golang.org/x/tools/go/ast/astutil.(*application).apply(0xc001eba240, {0x12f7a60, 0xc001b37950}, {0x1285731, 0x1015c0f}, 0x0, {0x12f7ab0, 0xc0021139f8})
	/Users/anacrolix/go/pkg/mod/golang.org/x/tools@v0.1.0/go/ast/astutil/rewrite.go:291 +0x6e5
golang.org/x/tools/go/ast/astutil.(*application).apply(0xc001eba240, {0x12f8320, 0xc00157e3b0}, {0x1285645, 0x28}, 0x28, {0x12f7a60, 0xc001b37950})
	/Users/anacrolix/go/pkg/mod/golang.org/x/tools@v0.1.0/go/ast/astutil/rewrite.go:417 +0x17b1
golang.org/x/tools/go/ast/astutil.Apply({0x12f7a60, 0xc001b37950}, 0xc00190c300, 0x0)
	/Users/anacrolix/go/pkg/mod/golang.org/x/tools@v0.1.0/go/ast/astutil/rewrite.go:52 +0x166
main.process(0xc0007ede60, 0xc001c7d580)
	/Users/anacrolix/go/pkg/mod/zombiezen.com/go/sqlite/cmd/zombiezen-sqlite-migrate@v0.2.1/migrate.go:304 +0x454
main.run({0x12f94a8, 0xc000104780}, 0x0, {0xc000010050, 0x1, 0x1})
	/Users/anacrolix/go/pkg/mod/zombiezen.com/go/sqlite/cmd/zombiezen-sqlite-migrate@v0.2.1/migrate.go:58 +0x4fa
main.main()
	/Users/anacrolix/go/pkg/mod/zombiezen.com/go/sqlite/cmd/zombiezen-sqlite-migrate@v0.2.1/migrate.go:35 +0x145
```

**Comment by zombiezen** [comment]
Thanks for the report! Run `go install zombiezen.com/go/sqlite/cmd/zombiezen-sqlite-migrate@v0.2.3` and try again. I was able to successfully migrate the project in my local testing. LMK if you encounter any other problems.

**Comment by anacrolix** [comment]
Thanks!
